# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 966057e93233f48a92a35dd196c02e41e1825517f7995db25ac60e2d549968bdd40aabc158d4abd1ede721854b1139e2b37ce3bb1f8e3497a241437052414476

test:
  secret_key_base: aa8f95bdecb04a62ff8fc29bf7240e66531d49ce3bf246ed368078e34c4d6a8c7d2ca42eb2c9b7c2984e210e527063c014defa01cc68d8da6612fc720d2edc99

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
